spring:
  cloud:
    gateway:
      routes:
        - id: report-service
          uri: http://localhost:8082
          predicates:
            - Path=/home
          filters:
            - AuthFilter

        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**

        - id: record-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthFilter

  application:
    name: hr-management-gateway
